language: cpp
compiler: gcc

# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_REF: github.com/childsish/graph.git

# Install dependencies
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ..
  - make
  - ./tests/graph_unit_tests
  - cd ../docs
  - doxygen graph.dox

# Deploy using travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/html
  github_token: $GITHUB_REPO_TOKEN
  on:
    branch: master
